Traceback (most recent call last):
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# A node n1 is created
n1 = Node(name="n1")
# A node n2 is created
n2 = Node(name="n2")
print(n1)
print(n2)

# Let us create more nodes
n3 = Node(name="n3")
n4 = Node(name="n4")
n5 = Node(name="n5")
n6 = Node(name="n6")
n7 = Node(name="n7")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# A node n1 is created[39;00m
[0;32m----> 2[0m n1 [38;5;241m=[39m [43mNode[49m(name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mn1[39m[38;5;124m"[39m)
[1;32m      3[0m [38;5;66;03m# A node n2 is created[39;00m
[1;32m      4[0m n2 [38;5;241m=[39m Node(name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mn2[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'Node' is not defined
NameError: name 'Node' is not defined

